import test from 'node:test';
import assert from 'node:assert/strict';
import { EXPECTED, validateRecords } from '../oracle.mjs';
import { summarize } from '../summarize.mjs';
const clone = value => structuredClone(value);
test('literal record oracle accepts the declared catalogue', () => assert.equal(validateRecords(clone(EXPECTED)), true));
test('oracle rejects missing row', () => assert.throws(() => validateRecords(clone(EXPECTED).slice(1))));
test('oracle rejects duplicate SKU', () => assert.throws(() => validateRecords([EXPECTED[0], EXPECTED[0], EXPECTED[2]])));
test('oracle rejects extra row', () => assert.throws(() => validateRecords([...EXPECTED, EXPECTED[0]])));
test('oracle rejects changed title', () => { const rows=clone(EXPECTED); rows[0].title='Other'; assert.throws(() => validateRecords(rows)); });
test('oracle rejects changed currency', () => { const rows=clone(EXPECTED); rows[0].currency='EUR'; assert.throws(() => validateRecords(rows)); });
test('oracle rejects changed price', () => { const rows=clone(EXPECTED); rows[0].price='0.00'; assert.throws(() => validateRecords(rows)); });
test('oracle rejects changed href', () => { const rows=clone(EXPECTED); rows[0].href='/wrong'; assert.throws(() => validateRecords(rows)); });
test('oracle rejects numeric price', () => { const rows=clone(EXPECTED); rows[0].price=19.95; assert.throws(() => validateRecords(rows)); });
test('oracle rejects undeclared fields', () => { const rows=clone(EXPECTED); rows[0].extra='x'; assert.throws(() => validateRecords(rows)); });
test('oracle rejects missing field', () => { const rows=clone(EXPECTED); delete rows[0].href; assert.throws(() => validateRecords(rows)); });
test('oracle rejects null input', () => assert.throws(() => validateRecords(null)));
test('oracle rejects reordered catalogue', () => assert.throws(() => validateRecords(clone(EXPECTED).reverse())));
test('summary rejects forged empty successful capture', () => assert.throws(() => summarize({rounds:3, runs:[], checks:0, passed_checks:0})));
test('summary rejects wrong browser', () => assert.throws(() => summarize({browser:'firefox',rounds:3,runs:[]})));
